### ISSUE TITLE
How do I read the information in syso.json in the program, such as ProductName、FileVersion、ProductVersion...

### ISSUE THREAD

**Issue by iquanxin** [hallazzang/syso#5]
I want read resource information in the program run.

**Comment by hallazzang** [comment]
@iquanxin I think you can check it in the executable's properties window. Right-click on the executable and see **Properties** and go to **Details** tab to see it.

**Comment by rodrigocfd** [comment]
@iquanxin You can read the EXE version information using [ResourceInfoLoad](https://pkg.go.dev/github.com/rodrigocfd/windigo@v0.0.0-20211109103335-16c5c15de5af/win#ResourceInfoLoad) from [Windigo](https://github.com/rodrigocfd/windigo) library:

```go
resNfo, _ := win.ResourceInfoLoad(win.HINSTANCE(0).GetModuleFileName())
verNfo, _ := resNfo.FixedFileInfo()
vMaj, vMin, vPat, _ := verNfo.ProductVersion() // version information, like 1.0.0

blocks := resNfo.Blocks() // each block contains one language
productName, _ := blocks[0].ProductName()
companyName, _ := blocks[0].CompanyName()
// and so on...
```

**Comment by iquanxin** [comment]
> @iquanxin You can read the EXE version information using [ResourceInfoLoad](https://pkg.go.dev/github.com/rodrigocfd/windigo@v0.0.0-20211109103335-16c5c15de5af/win#ResourceInfoLoad) from [Windigo](https://github.com/rodrigocfd/windigo) library:
> 
> ```go
> resNfo, _ := win.ResourceInfoLoad(win.HINSTANCE(0).GetModuleFileName())
> verNfo, _ := resNfo.FixedFileInfo()
> vMaj, vMin, vPat, _ := verNfo.ProductVersion() // version information, like 1.0.0
> 
> blocks := resNfo.Blocks() // each block contains one language
> productName, _ := blocks[0].ProductName()
> companyName, _ := blocks[0].CompanyName()
> // and so on...
> ```

Perfect.
